[api]
client_id = ""
client_secret = "" 
refresh_token =  ""
drive_id = ""
api_url = "https://api.onedrive.com/v1.0/"
auth_url = "https://login.live.com/oauth20_authorize.srf"
token_url = "https://login.live.com/oauth20_token.srf"
